// Generated by CoffeeScript 1.12.3
(function() {
  if (window.samples == null) {
    window.samples = {};
  }

  window.samples['count-up'] = '(do\n	(set! i 0)\n	(while (< i 99)\n		(do\n			(print-int i)\n			(set! i (+ i 1)))))';

}).call(this);
