// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var convert, handlers, makeEnv, makePlayfield;

  handlers = fungify.handlers, makePlayfield = fungify.makePlayfield, makeEnv = fungify.makeEnv;

  convert = function(root) {
    var env, playfield, programLoc, recurse;
    playfield = makePlayfield();
    env = makeEnv();
    recurse = function(node, line, column) {
      var handler;
      handler = handlers.get(node.type);
      return handler(recurse, node, playfield.place, env.resolve, line, column);
    };
    playfield.place(0, 1, 'v');
    programLoc = recurse(root, 1, 1);
    playfield.place(programLoc.line, 1, '@');
    return playfield.stringify();
  };

  if (window.fungify == null) {
    window.fungify = {};
  }

  Object.assign(window.fungify, {
    convert: convert
  });

}).call(this);
