// Generated by CoffeeScript 1.12.3
(function() {
  'use strict';
  var makeEnv;

  makeEnv = function() {
    var count, mapping, resolve;
    count = 0;
    mapping = new Map;
    resolve = function(name) {
      var prevCount;
      if (mapping.has(name)) {
        return mapping.get(name);
      } else {
        prevCount = count;
        mapping.set(name, count);
        count++;
        return prevCount;
      }
    };
    return {
      resolve: resolve
    };
  };

  if (window.fungify == null) {
    window.fungify = {};
  }

  Object.assign(window.fungify, {
    makeEnv: makeEnv
  });

}).call(this);
